ComitLibraryMvc/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ComitLibraryMvc.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using ComitLibrary;
using ComitLibrary.Models;

namespace ComitLibraryMvc.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private LibrarySystem _library;
        private UserManager<IdentityUser> _userManager;

        public BookController(LibrarySystem library, UserManager<IdentityUser> userManager)
        {
            _library = library;
            _userManager = userManager;

        }

        // GET Book/Index
        public IActionResult Index()
        {
            List<Book> books = _library.GetAllBooks(UserId());
            return View(books);
        }

        public IActionResult Details(Guid id) {
            
            var book = _library.GetBook(id, UserId());

            return View(book);
        }

        public IActionResult Edit(Guid id) {
            // Get the book from the librarySystem
            var book = _library.GetBook(id, UserId());

            // build the view model
            var bookViewModel = new BookViewModel() {
                Author = book.Author,
                Title = book.Title,
                Year = book.Year,
            };


            // send the view model
            ViewBag.IsEditing = true;
            return View("Form", bookViewModel);
        }

        public IActionResult Form() {
            ViewBag.IsEditing = false;
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(BookViewModel newBook) {

            if (ModelState.IsValid) {
                var bookToCreate = new Book() {
                    Title = newBook.Title,
                    Author = newBook.Author,
                    IsCheckedOut = false,
                    Id = Guid.NewGuid(),
                    Year = newBook.Year,
                    UserId = UserId(),
                };
                _library.AddNewBook(bookToCreate);

                return RedirectToAction("Index");
            } else {
                return View("Form", newBook);
            }
        }


        [HttpPost]
        public IActionResult Update(BookViewModel updatedBook) {
            if (ModelState.IsValid) {
                var existingBook = _library.GetBook(updatedBook.Id.Value, UserId());
                var book = new Book() {
                    Title = updatedBook.Title,
                    Author = updatedBook.Author,
                    IsCheckedOut = existingBook.IsCheckedOut,
                    Id = updatedBook.Id.Value,
                    Year = updatedBook.Year,
                    UserId = UserId()
                };
                _library.UpdateBook(book);
                return RedirectToAction("Index");
            } else {
                ViewBag.IsEditing = true;
                return View("Form", updatedBook);
            }

        }

        [HttpPost]
        public IActionResult Delete(Guid id) {
            _library.DeleteBookById(id, UserId());
            return RedirectToAction("Index");
        }


        public IActionResult Search() {
            var search = new SearchViewModel() {
                Title = "",
                SearchResults = new List<Book>()
            };
            return View(search);
        }

        [HttpPost]
        public IActionResult Search(SearchViewModel search) {
            search.SearchResults = _library.SearchForBook(search.Title, UserId());
            return View(search);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private Guid UserId() {
            string stringUserId = _userManager.GetUserId(User);
            return Guid.Parse(stringUserId);
        }
    }
}

ComitLibraryMvc/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ComitLibraryMvc.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using ComitLibrary;
using ComitLibrary.Models;

namespace ComitLibraryMvc.Controllers
{
    [Authorize]
    public class LoanController : Controller
    {
        private LibrarySystem _library;
        private UserManager<IdentityUser> _userManager;

        public LoanController(LibrarySystem library, UserManager<IdentityUser> userManager)
        {
            _library = library;
            _userManager = userManager;
        }

        public IActionResult Index() {
            var loans = _library.GetAllActiveLoans(UserId());
            return View(loans);
        }

        public IActionResult Create(Guid id) {
            var patrons = _library.GetAllPatrons(UserId());
            var patronList = patrons.Select(x => new {x.Id, x.FullName}).ToList();
            var selectList = new SelectList(patronList, "Id","FullName");
            
            var book = _library.GetBook(id, UserId());

            var loanViewModel = new LoanViewModel() {
                BookId = id,
                PatronList = selectList,
                Title = $"{book.Title} ({book.Author})"
            };
            return View(loanViewModel);
        }
        
        [HttpPost]
        public IActionResult Create(LoanViewModel newLoan) {
            if (ModelState.IsValid) {
                _library.CheckoutBook(newLoan.PatronId, newLoan.BookId, UserId());
                return RedirectToAction("Index", "Book");
            } else {
                return View(newLoan);
            }
        }

        public IActionResult Return(Guid id) { 
            _library.ReturnBook(id, UserId());
            return RedirectToAction("Details", "Book", new { id });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private Guid UserId() {
            string stringUserId = _userManager.GetUserId(User);
            return Guid.Parse(stringUserId);
        }
    }
}

ComitLibraryMvc/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ComitLibraryMvc.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

using ComitLibrary;
using ComitLibrary.Models;

namespace ComitLibraryMvc.Controllers
{
    [Authorize]
    public class PatronController : Controller
    {
        private LibrarySystem _library;
        private UserManager<IdentityUser> _userManager;

        public PatronController(LibrarySystem library, UserManager<IdentityUser> userManager)
        {
            _library = library;
            _userManager = userManager;
        }

        public IActionResult Index() {
            var patrons = _library.GetAllPatrons(UserId());
            return View(patrons);
        }

        public IActionResult Create(Guid id) {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(PatronViewModel newPatron) {
            if (ModelState.IsValid) {
                var patron = new Patron(Guid.NewGuid(), newPatron.FirstName, newPatron.LastName, UserId());
                _library.AddPatron(patron);
                return RedirectToAction("Index");
            } else {
                return View(newPatron);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private Guid UserId() {
            string stringUserId = _userManager.GetUserId(User);
            return Guid.Parse(stringUserId);
        }
    }
}

ComitLibraryMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comit Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">ComIT Library</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patron" asp-action="Index">Patrons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loan" asp-action="Index">Loans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Search">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ComitLibraryMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
$(document).ready( function () {
    $('#books-table').DataTable({
        searching: false
    });
});
</script>